const GET_USERS = "GET_USERS";
const SHOW_DIALOG = "SHOW_DIALOG";
const SET_SEARCH_STRING = "SET_SEARCH_STRING";
const ADD_USER = "ADD_USER";
const REMOVE_USER = "REMOVE_USER";
const SET_SEARCH_DIALOG = "SET_SEARCH_DIALOG";

export default {
  GET_USERS,
  SHOW_DIALOG,
  SET_SEARCH_STRING,
  ADD_USER,
  REMOVE_USER,
  SET_SEARCH_DIALOG
};
